.default_image_build_setup_template: &default_image_build_setup
  image: docker:18.09.7
  services:
    - name: docker:18.09.7-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

######################################
## Build docker image ##
######################################
## build new image with latest tag - master branch
build:image:master:
  stage: build image
  <<: *default_image_build_setup
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  retry: 2

stages:
  - build image
